version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./local/nginx.conf/:/etc/nginx/conf.d/default.conf
      - .:/var/www/webgpu/
  # node:
  #   image: node:20.9.0
  #   working_dir: /var/www/webgpu
  #   volumes:
  #     - .:/var/www/webgpu/
  #   command: npm run dev